"""Criando relacionamento entre fornecedor e conta

Revision ID: d31b9cb07e94
Revises: 37cde5e1f772
Create Date: 2024-09-16 21:24:46.763227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31b9cb07e94'
down_revision: Union[str, None] = '37cde5e1f772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_pagar_receber', sa.Column('fornecedor_cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contas_pagar_receber', 'fornecedor_cliente', ['fornecedor_cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contas_pagar_receber', type_='foreignkey')
    op.drop_column('contas_pagar_receber', 'fornecedor_cliente_id')
    # ### end Alembic commands ###
